language: python
os: linux
sudo: required
services:
  - docker
python:
  - "2.7"
before_install:
  - pip install -U yamllint ansible
script:
  - yamllint roles
  - ansible-playbook -i inventory/local-tests.ini cluster.yml -vvv --syntax-check
  - ansible-playbook -i inventory/local-tests.ini upgrade-cluster.yml -vvv --syntax-check
  - ansible-playbook -i inventory/local-tests.ini addons.yml -vvv --syntax-check
  - ansible-playbook -i inventory/local-tests.ini reset-cluster.yml -vvv --syntax-check
