---

- name: Ensure etcd PKI directory already exists
  file: path={{ etcd_pki_dir }} state=directory
  register: create_etcd_pki_dir

- name: Copy etcd certificates and keys
  vars:
    files:
      - "{{ etcd_ca }}"
      - "{{ etcd_ca_key }}"
      - "{{ etcd_cert }}"
      - "{{ etcd_cert_key }}"
  import_role:
    name: common/copy-files

- name: Ensure etcd config directory exists
  file:
    path: "{{ etcd_config_dir }}"
    recurse: yes
    state: directory

- name: Ensure etcd data directory exists
  file:
    path: "{{ etcd_data_dir }}"
    recurse: yes
    state: directory

- name: Copy etcd config template file
  template: src=etcd-config.yml.j2 dest={{ etcd_config_file }}

- name: Copy etcd systemd service file
  template:
    src: etcd.service.j2
    dest: "{{ systemd_service_dir }}/etcd.service"
    owner: root
    group: root
    mode: 0644
  register: change_etcd

- name: Enable and restart etcd
  when: change_etcd
  systemd:
    name: etcd
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_etcd
