---

etcd_listen_addr: "{% if etcd_iface != '' %}{{ hostvars[inventory_hostname]['ansible_' + etcd_iface].ipv4.address }}
{%- else %}{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}{% endif %}"
etcd_listen_client_urls: "https://127.0.0.1:2379,https://{{ etcd_listen_addr }}:2379"
etcd_listen_peer_urls: "https://{{ etcd_listen_addr }}:2380"
etcd_advertise_client_urls: "https://{{ etcd_listen_addr }}:2379"
etcd_initial_advertise_peer_urls: "https://{{ etcd_listen_addr }}:2380"

etcd_initial_cluster_state: new
etcd_initial_token: k8s-etcd-cluster
