---

kube_version: 1.16.0

# Container runtime,
# Supported: docker, nvidia-docker, containerd.
container_runtime: docker

# Container network,
# Supported: calico, flannel.
cni_enable: true
container_network: calico

# Kubernetes HA extra variables.
vip_interface: "enp0s8"
vip_address: 192.168.56.100

# Kubernetes extra addons
enable_ingress: false
enable_dashboard: true
enable_logging: false
enable_monitoring: false
enable_metric_server: false